sudo: false
language: python

python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - pip_download_cache

env:
  - TRAVIS="True"

install:
  - pip install git+https://github.com/aneumeier/category#master
  - pip install coveralls
script:
  - coverage run --source=category categorytest.py -m py.test
after_success:
  - coveralls
notifications:
  email: false
